version: '3'
services:
  web:
    image: ghcr.io/demathias/evecorpchecker
    restart: unless-stopped
    networks:
      - evocorpchecker-internal
      - shared
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.services.cc.loadbalancer.server.port=80"
      - "traefik.http.routers.cc.rule=Host(`cc.ca-corp.org`)"
      - "traefik.http.routers.cc.entrypoints=web"
      - "traefik.http.routers.cc-secure.rule=Host(`cc.ca-corp.org`)"
      - "traefik.http.routers.cc-secure.entrypoints=websecure"
      - "traefik.http.routers.cc-secure.tls=true"
      - "traefik.http.routers.cc-secure.tls.certresolver=primary"

  # db:
  #   image: mariadb:10.5
  #   volumes:
  #     - /docker/evecorpchecker/data/db:/var/lib/mysql
  #   restart: unless-stopped
  #   env_file: 
  #     - .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
  #     MYSQL_DATABASE: evecorpchecker
  #     MYSQL_USER: evecorpchecker
  #     MYSQL_PASSWORD: ${MYSQL_PASS}
  #   networks:
  #     - evocorpchecker-internal

networks:
  shared:
    external: true
