version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - evocorpchecker-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.services.cc.loadbalancer.server.port=80"
      - "traefik.http.routers.cc.rule=Host(`cc.ca-corp.org`)"
      - "traefik.http.routers.cc.entrypoints=web"
      - "traefik.http.routers.cc-secure.rule=Host(`cc.ca-corp.org`)"
      - "traefik.http.routers.cc-secure.entrypoints=websecure"
      - "traefik.http.routers.cc-secure.tls=true"
      - "traefik.http.routers.cc-secure.tls.certresolver=primary"
  
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password # change this with a secure password
      MYSQL_DATABASE: evecorpchecker
      MYSQL_USER: evecorpchecker
      MYSQL_PASSWORD: password # change this with a secure password
    networks:
      - evocorpchecker-internal

networks:
  evocorpchecker-internal:

volumes:
  db_data:
